name: Build LaTeX document

on: [push, workflow_dispatch]

jobs:
  build_latex:
  
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: main.tex
          
      - name: Upload PDF file
        uses: actions/upload-artifact@v3
        with:
          name: PDF
          path: main.pdf
      
      - name: Run Latex2HTML
        run: |
          sudo apt-get latex2html
          export TITLE = Theory Group Seminar Notes
          latex2html main.tex
          
      - name: Commit files
        run: |
          cd main
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          ssh: true
          branch: gh-pages
