name: Build LaTeX document

on: [push, workflow_dispatch]

jobs:
  build_latex:
  
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: main.tex
          
      - name: Upload PDF file
        uses: actions/upload-artifact@v3
        with:
          name: PDF
          path: main.pdf
      
      - name: Run Latex2HTML
        run: |
          sudo apt-get install latex2html
          latex2html -t "Theory Group Seminar Notes" -no_navigation 1 main.tex
          
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: main # The folder the action should deploy.
